version: '2'

services:
    
    web:
        build: nginx
        image: maxlab/nginx
        restart: always
        env_file: .env
        depends_on:
            - php7xdebug
            - mysql
            - pgsql
            - redis
            - mailcatcher
        volumes:
            - ./nginx/nginx:/etc/nginx
            - ./nginx/nginx/sites-available/vhost/symfony.env.tpl:/tmp/nginx/symfony.env.tpl
        volumes_from:
            - php7xdebug
        links:
            - php7xdebug:fpm7
            - mailcatcher
        ports:
            - 80:80
            - 443:433
        command: /bin/bash -c "envsubst '$$SYMFONY_ENV' < /tmp/nginx/symfony.env.tpl > /etc/nginx/sites-available/vhost/symfony && nginx"
        
        
    mysql:
        image: mysql:5.7
        env_file: .env
        ports:
            - 3307:3306
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/mysql:/var/lib/mysql
        restart: always
        
        
    pgsql:
        image: postgres:9.6
        env_file: .env
        ports:
            - 5433:5432
        volumes:
            - ./pgsql/pgsql:/var/lib/postgresql
        restart: always
        
        
    redis:
        image: redis:3.0
        restart: always
        volumes: 
            - ./redis/redis:/data
        ports:
            - 6379:6379
            
        
    mailcatcher:
        image: schickling/mailcatcher
        restart: always
        
        
    php7xdebug:
        env_file: .env
        build: 
            context: ./php7xdebug
        image: maxlab/php7xdebug
        restart: always
        volumes:
            - ./workspace:/data
        links:
            - pgsql
            - mysql
            - mailcatcher
            - redis
            - elasticsearch
            
            
    php5apache:
        build: php5apache
        image: maxlab/php5apache
        restart: always        
        volumes:
            - ./php5apache/conf/apache:/etc/apache2
            - ./php5apache/conf/php/php.ini:/usr/local/etc/php/conf.d/my.ini
        env_file: .env
        volumes_from:
            - php7xdebug
        depends_on:
            - mysql
            - redis
            - mailcatcher
        links:
            - php7xdebug:fpm7
            - mailcatcher
        ports:
            - 81:80
            - 444:443
            
            
    php7console:
        build: php7console
        container_name: php7console 
        image: maxlab/php7console
        env_file: .env
        restart: always        
        volumes_from:
            - php7xdebug 
        tty: true
        
        
    elasticsearch: 
        build: elasticsearch
        volumes:
            - ./elasticsearch/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        tty: true
